language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/greeted_names
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database greeted_names;' -U postgres
  - psql -U postgres -d greeted_names -a -f tables.sql 

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2