language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/greetedNames
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database greetedNames;' -U postgres
  - psql -U postgres -d greetedNames -a -f tables.sql 

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2